### PR TITLE
add unfold function to MessagePanelView

### PR DESCRIPTION
**Pull request by grz0zrg**
The toggle() function was not enough.

### CODE REVIEW

**Comment by tcarlsen** [comment]
do we need both then?

**Comment by grz0zrg** [comment]
Yes, adding a fold function would be better also so that the folding/unfolding of the panel can be forced through the API.

**Comment by tcarlsen** [comment]
I will test this out asap.

**Comment by tcarlsen** [comment]
sry for the long wait!

**Pull request merged**
