### PR TITLE
Make the heading toggle the panel. Closes #57

### LINKED ISSUE #57: would be great if the title toggled the panel
Would be awesome if I could click this : 

image

Cause clicking this is a bit frustrating: 
image

Or even just title would be great.

### PR DESCRIPTION
**Pull request by basarat**
Why else would you click the heading?

### CODE REVIEW

**Comment by tcarlsen** [comment]
will this not conflict with click on heading to get to line in Fold Mode???

**Comment by basarat** [comment]
No. Clicking on the error in fold mode still takes you to the error.

**Comment by tcarlsen** [comment]
thx will merge this as soon as I have done a little testing :+1:  thx!

**Comment by tcarlsen** [comment]
merges into branch `v1.2.0` https://github.com/tcarlsen/atom-message-panel/commit/a5f97acb622fbaa69bd2ada8f378c0cffd4c8412

**Pull request closed without merging**
