### PR TITLE
Fixed atom script error

### PR DESCRIPTION
**Pull request by neur0hak**
fixed this issue https://github.com/rgbkrk/atom-script/issues/1984

### CODE REVIEW

**Review by juftin — COMMENTED** [review]
This resolved the issue on my end. Thanks @neur0hak !

**Comment by Alex815O** [comment]
After this change, I run into a new bug. The message panel disappears and does not pop up again.

**Comment by tcarlsen** [comment]
Im not really using this lib myself anymore, so I happy to see others still using it and wanna make PR's. but seeing that @Alex815O gets a new error stops me for merging. @neur0hak can you please look into this and fix before I merge?

**Comment by neur0hak** [comment]
> After this change, I run into a new bug. The message panel disappears and does not pop up again.

I think the bug is occuring on the script code, not on atom-message-panel
I recommend the window doesn't close and minimize

**Comment by tcarlsen** [comment]
this is now in `1.3.1`

**Comment by ADepic** [comment]
this commit did not fix this issue at all

**Pull request merged**
